kind: pipeline
type: docker
name: ci

platform:
  os: linux
  arch: amd64

common_cache_settings: &common_cache_settings
  bucket: dvla-drone1-cache-714782054810
  region: eu-west-2
  encryption: AES256
  endpoint: https://s3.eu-west-2.amazonaws.com

restore_cache: &restore_cache
  restore: true

rebuild_cache: &rebuild_cache
  rebuild: true

npm_cache_settings: &npm_cache_settings
  cache_key: '{{ checksum "package-lock.json" }}'
  mount:
    - 'node_modules'

steps:
  - name: secret scan
    pull: if-not-exists
    image: ecr.tooling.dvla.gov.uk/utilities-ci-tools/ci-secret-scan

  - name: pull npm cache
    image: ecr.tooling.dvla.gov.uk/ce/drone-cache
    depends_on: ["secret scan"]
    settings:
      <<: [*common_cache_settings, *npm_cache_settings, *restore_cache]

  - name: install
    pull: if-not-exists
    image: &base--image ecr.tooling.dvla.gov.uk/base-images/serverless:0.0.20
    commands:
      - npm config set unsafe-perm true
      - npm ci
    environment:
      NPM_CONFIG_REGISTRY: https://nexus.tooling.dvla.gov.uk/repository/npm-group/

  - name: push npm cache
    image: ecr.tooling.dvla.gov.uk/ce/drone-cache
    depends_on: ['install']
    settings:
      <<: [*common_cache_settings, *npm_cache_settings, *rebuild_cache]

  - name: audit
    pull: if-not-exists
    image: *base--image
    failure: ignore
    commands:
      - npm run audit
    depends_on:
      - install

  - name: build
    pull: if-not-exists
    image: *base--image
    commands:
      - npm run build
    depends_on:
      - install

  - name: lint
    pull: if-not-exists
    image: *base--image
    commands:
      - npm run lint --workspaces
    depends_on:
      - build

  - name: outdated
    pull: if-not-exists
    image: *base--image
    failure: ignore
    commands:
     - npm run outdatedRoot
     - npm run outdated
    depends_on:
     - install

  - name: test
    pull: if-not-exists
    image: *base--image
    commands:
      - npm run test
    depends_on:
      - build

  - name: Cloudformation Analysis
    pull: if-not-exists
    image: ecr.tooling.dvla.gov.uk/utilities-ci-tools/ci-verify-cloudformation
    failure: ignore
    depends_on:
      - test
    settings:
      template_dir: ./packages/lab-common-cdk/coverage/templates

  - name: publish
    image: *base--image
    environment: &env-npm-nexus
      NPM_CONFIG_REGISTRY: https://nexus.tooling.dvla.gov.uk/repository/npm-group/
    commands:
      - npm run release
      - npm run publish
    depends_on:
      - test
    when:
      branch: [master]

  - name: teams notify success
    image: ecr.tooling.dvla.gov.uk/utilities-ci-tools/ci-notifier:latest
    settings:
      webhook:
        from_secret: TEAMS_WEBHOOK # pragma: allowlist secret
    depends_on: ['publish']
    when:
      branch: [master]
      status:
        - success

  - name: teams notify failure
    image: ecr.tooling.dvla.gov.uk/utilities-ci-tools/ci-notifier:latest
    settings:
      webhook:
        from_secret: TEAMS_WEBHOOK # pragma: allowlist secret
    depends_on: ['test']
    when:
      status:
        - failure
