kind: pipeline
type: docker
name: ci

platform:
  os: linux
  arch: amd64

steps:
  - name: install
    pull: if-not-exists
    image: &base--image node:lts
    commands:
      - npm config set unsafe-perm true
      - npm ci
      - npm run bootstrap-ci

#  - name: outdated
#    pull: if-not-exists
#    image: *base--image
#    failure: ignore
#    commands:
#      - npm run outdated
#    depends_on:
#      - install
#    environment: *env-npm-nexus

  - name: audit
    pull: if-not-exists
    image: *base--image
    failure: ignore
    commands:
      - npm run audit
    depends_on:
      - install

  - name: build
    pull: if-not-exists
    image: *base--image
    commands:
      - npm run build
    depends_on:
      - install

  - name: lint
    pull: if-not-exists
    image: *base--image
    commands:
      - npm run lint
    depends_on:
      - build

  - name: test
    pull: if-not-exists
    image: *base--image
    commands:
      - npm run test
    depends_on:
      - build

  - name: publish
    image: *base--image
    environment: &env-npm-nexus
      NPM_CONFIG_REGISTRY: https://nexus.tooling.dvla.gov.uk/repository/npm-group/
    commands:
      - npm run publish
    depends_on:
      - test
    when:
      branch: [master]
