kind: pipeline
type: docker
name: ci

platform:
  os: linux
  arch: amd64

steps:
  - name: install
    pull: if-not-exists
    image: &base--image ecr.tooling.dvla.gov.uk/base-images/serverless:0.0.20
    commands:
      - npm config set unsafe-perm true
      - npm ci
      - npm run bootstrap-ci
    environment:
      NPM_CONFIG_REGISTRY: https://nexus.tooling.dvla.gov.uk/repository/npm-group/

  - name: audit
    pull: if-not-exists
    image: *base--image
    failure: ignore
    commands:
      - npm run audit
    depends_on:
      - install

  - name: build
    pull: if-not-exists
    image: *base--image
    commands:
      - npm run build
    depends_on:
      - install

  - name: lint
    pull: if-not-exists
    image: *base--image
    commands:
      - npm run lint
    depends_on:
      - build

  - name: outdated
    pull: if-not-exists
    image: *base--image
    failure: ignore
    commands:
     - npm run outdated
    depends_on:
     - install

  - name: test
    pull: if-not-exists
    image: *base--image
    commands:
      - npm run test
    depends_on:
      - build

  - name: Cloudformation Analysis
    pull: if-not-exists
    image: ecr.tooling.dvla.gov.uk/utilities-ci-tools/ci-verify-cloudformation
    failure: ignore
    depends_on:
      - test
    settings:
      template_dir: ./packages/lab-common-cdk/coverage/templates

  - name: publish
    image: *base--image
    environment: &env-npm-nexus
      NPM_CONFIG_REGISTRY: https://nexus.tooling.dvla.gov.uk/repository/npm-group/
    commands:
      - npm run publish
    depends_on:
      - test
    when:
      branch: [master]
